# Configuration file for Dependabot (https://github.com/dependabot)

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 1
    schedule:
      interval: daily
      time: "05:00"
    cooldown:
      default-days: 2
    labels:
      - dependencies
    groups:
      stryker:
        patterns:
          - "@stryker-mutator/*"
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 1
    schedule:
      interval: daily
      time: "05:00"
    cooldown:
      default-days: 2
    labels:
      - dependencies
