name: Windows
on:
  pull_request:
    paths:
      - .github/workflows/checks-windows.yml
      - .github/workflows/reusable-fuzz.yml
      - src/win/**
      - test/fuzz/**
  push:
    paths:
      - .github/workflows/checks-windows.yml
      - .github/workflows/reusable-fuzz.yml
      - src/win/**
      - test/fuzz/**
    branches:
      - main

permissions: read-all

jobs:
  fuzz:
    name: Fuzz
    uses: ericcornelissen/shescape/.github/workflows/reusable-fuzz.yml@main
    with:
      duration: 5m
      platform: windows
