name: Unix
on:
  pull_request:
    paths:
      - .github/workflows/checks-unix.yml
      - .github/workflows/reusable-fuzz.yml
      - src/unix.js
      - test/fuzz/**
  push:
    paths:
      - .github/workflows/checks-unix.yml
      - .github/workflows/reusable-fuzz.yml
      - src/unix.js
      - test/fuzz/**
    branches:
      - main

permissions: read-all

jobs:
  fuzz:
    name: Fuzz
    uses: ericcornelissen/shescape/.github/workflows/reusable-fuzz.yml@pin-actions-runner-images
    with:
      duration: 5m
      platform: unix
